#!/usr/bin/env python3
"""
Unit tests for lock file parser functions.
"""

import unittest
import sys
import os
from pathlib import Path
from unittest.mock import patch, mock_open
import json
import tempfile

# Add parent directory to path to import the module
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from analyze_bun_lock import (
    detect_lock_file_format,
    parse_bun_lock,
    parse_npm_lock,
    parse_yarn_lock,
    parse_pnpm_lock,
    parse_deno_lock,
    parse_lock_file
)


class TestDetectLockFileFormat(unittest.TestCase):
    """Test lock file format detection."""
    
    def test_detect_bun_lock(self):
        """Test detection of bun.lock file."""
        with tempfile.NamedTemporaryFile(mode='w', suffix='', delete=False, dir=tempfile.gettempdir()) as f:
            temp_dir = os.path.dirname(f.name)
            temp_path = os.path.join(temp_dir, 'bun.lock')
        
        try:
            with open(temp_path, 'w') as f:
                f.write('{}')
            result = detect_lock_file_format(temp_path)
            self.assertEqual(result, 'bun')
        finally:
            if os.path.exists(temp_path):
                os.unlink(temp_path)
    
    def test_detect_npm_lock(self):
        """Test detection of package-lock.json file."""
        with tempfile.NamedTemporaryFile(mode='w', suffix='', delete=False, dir=tempfile.gettempdir()) as f:
            temp_dir = os.path.dirname(f.name)
            temp_path = os.path.join(temp_dir, 'package-lock.json')
        
        try:
            with open(temp_path, 'w') as f:
                f.write('{}')
            result = detect_lock_file_format(temp_path)
            self.assertEqual(result, 'npm')
        finally:
            if os.path.exists(temp_path):
                os.unlink(temp_path)
    
    def test_detect_yarn_lock(self):
        """Test detection of yarn.lock file."""
        with tempfile.NamedTemporaryFile(mode='w', suffix='', delete=False, dir=tempfile.gettempdir()) as f:
            temp_dir = os.path.dirname(f.name)
            temp_path = os.path.join(temp_dir, 'yarn.lock')
        
        try:
            with open(temp_path, 'w') as f:
                f.write('# THIS IS AN AUTOGENERATED FILE')
            result = detect_lock_file_format(temp_path)
            self.assertEqual(result, 'yarn')
        finally:
            if os.path.exists(temp_path):
                os.unlink(temp_path)
    
    def test_detect_pnpm_lock(self):
        """Test detection of pnpm-lock.yaml file."""
        with tempfile.NamedTemporaryFile(mode='w', suffix='', delete=False, dir=tempfile.gettempdir()) as f:
            temp_dir = os.path.dirname(f.name)
            temp_path = os.path.join(temp_dir, 'pnpm-lock.yaml')
        
        try:
            with open(temp_path, 'w') as f:
                f.write('lockfileVersion: 6.0')
            result = detect_lock_file_format(temp_path)
            self.assertEqual(result, 'pnpm')
        finally:
            if os.path.exists(temp_path):
                os.unlink(temp_path)
    
    def test_detect_deno_lock(self):
        """Test detection of deno.lock file."""
        with tempfile.NamedTemporaryFile(mode='w', suffix='', delete=False, dir=tempfile.gettempdir()) as f:
            temp_dir = os.path.dirname(f.name)
            temp_path = os.path.join(temp_dir, 'deno.lock')
        
        try:
            with open(temp_path, 'w') as f:
                f.write('{}')
            result = detect_lock_file_format(temp_path)
            self.assertEqual(result, 'deno')
        finally:
            if os.path.exists(temp_path):
                os.unlink(temp_path)


class TestParseBunLock(unittest.TestCase):
    """Test Bun lock file parser."""
    
    def setUp(self):
        """Set up test fixtures."""
        self.test_dir = Path(__file__).parent / 'fixtures'
        self.sample_file = self.test_dir / 'sample_bun.lock'
    
    def test_parse_bun_lock_basic(self):
        """Test basic parsing of bun.lock file."""
        if self.sample_file.exists():
            packages = parse_bun_lock(str(self.sample_file))
            
            self.assertIsInstance(packages, list)
            self.assertGreater(len(packages), 0)
            
            # Check tuple structure
            for pkg_name, version in packages:
                self.assertIsInstance(pkg_name, str)
                self.assertIsInstance(version, str)
            
            # Verify specific packages from sample_bun.lock fixture
            package_dict = {pkg[0]: pkg[1] for pkg in packages}
            self.assertIn('react', package_dict)
            self.assertEqual(package_dict['react'], '18.2.0')
            self.assertIn('@babel/core', package_dict)
            self.assertEqual(package_dict['@babel/core'], '7.27.4')
            self.assertIn('lodash', package_dict)
            self.assertEqual(package_dict['lodash'], '4.17.21')
            
            # Verify we have exactly 3 packages from the fixture
            self.assertEqual(len(packages), 3)
    
    def test_parse_bun_lock_scoped_package(self):
        """Test parsing scoped packages in bun.lock."""
        bun_data = {
            "packages": {
                "@babel/core": ["@babel/core@7.27.4"]
            }
        }
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.lock', delete=False) as f:
            json.dump(bun_data, f)
            temp_path = f.name
        
        try:
            packages = parse_bun_lock(temp_path)
            self.assertEqual(len(packages), 1)
            self.assertEqual(packages[0], ('@babel/core', '7.27.4'))
        finally:
            os.unlink(temp_path)
    
    def test_parse_bun_lock_regular_package(self):
        """Test parsing regular packages in bun.lock."""
        bun_data = {
            "packages": {
                "react": ["react@18.2.0"]
            }
        }
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.lock', delete=False) as f:
            json.dump(bun_data, f)
            temp_path = f.name
        
        try:
            packages = parse_bun_lock(temp_path)
            self.assertEqual(len(packages), 1)
            self.assertEqual(packages[0], ('react', '18.2.0'))
        finally:
            os.unlink(temp_path)
    
    def test_parse_bun_lock_empty_packages(self):
        """Test parsing bun.lock with empty packages section."""
        bun_data = {
            "packages": {}
        }
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.lock', delete=False) as f:
            json.dump(bun_data, f)
            temp_path = f.name
        
        try:
            packages = parse_bun_lock(temp_path)
            self.assertEqual(len(packages), 0)
        finally:
            os.unlink(temp_path)
    
    def test_parse_bun_lock_multiple_versions(self):
        """Test parsing bun.lock with multiple package versions."""
        bun_data = {
            "packages": {
                "react": ["react@18.2.0"],
                "react-dom": ["react-dom@18.2.0"],
                "@types/react": ["@types/react@18.0.0"]
            }
        }
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.lock', delete=False) as f:
            json.dump(bun_data, f)
            temp_path = f.name
        
        try:
            packages = parse_bun_lock(temp_path)
            self.assertEqual(len(packages), 3)
            
            package_names = [pkg[0] for pkg in packages]
            self.assertIn('react', package_names)
            self.assertIn('react-dom', package_names)
            self.assertIn('@types/react', package_names)
        finally:
            os.unlink(temp_path)


class TestParseNpmLock(unittest.TestCase):
    """Test npm lock file parser."""
    
    def setUp(self):
        """Set up test fixtures."""
        self.test_dir = Path(__file__).parent / 'fixtures'
        self.sample_file = self.test_dir / 'sample_package_lock.json'
    
    def test_parse_npm_lock_v7(self):
        """Test parsing npm v7+ package-lock.json."""
        npm_data = {
            "lockfileVersion": 3,
            "packages": {
                "node_modules/react": {
                    "version": "18.2.0"
                },
                "node_modules/@babel/core": {
                    "version": "7.27.4"
                }
            }
        }
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
            json.dump(npm_data, f)
            temp_path = f.name
        
        try:
            packages = parse_npm_lock(temp_path)
            self.assertGreaterEqual(len(packages), 2)
            
            # Check if packages are extracted correctly
            package_names = [pkg[0] for pkg in packages]
            self.assertIn('react', package_names)
            self.assertIn('@babel/core', package_names)
        finally:
            os.unlink(temp_path)
    
    def test_parse_npm_lock_v6(self):
        """Test parsing npm v6 package-lock.json (nested dependencies)."""
        npm_data = {
            "lockfileVersion": 1,
            "dependencies": {
                "react": {
                    "version": "18.2.0"
                },
                "@babel/core": {
                    "version": "7.27.4"
                }
            }
        }
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
            json.dump(npm_data, f)
            temp_path = f.name
        
        try:
            packages = parse_npm_lock(temp_path)
            self.assertEqual(len(packages), 2)
            
            package_dict = {pkg[0]: pkg[1] for pkg in packages}
            self.assertEqual(package_dict['react'], '18.2.0')
            self.assertEqual(package_dict['@babel/core'], '7.27.4')
        finally:
            os.unlink(temp_path)
    
    def test_parse_npm_lock_empty_packages(self):
        """Test parsing npm lock with empty packages section."""
        npm_data = {
            "lockfileVersion": 3,
            "packages": {}
        }
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
            json.dump(npm_data, f)
            temp_path = f.name
        
        try:
            packages = parse_npm_lock(temp_path)
            self.assertEqual(len(packages), 0)
        finally:
            os.unlink(temp_path)
    
    def test_parse_npm_lock_skip_root_package(self):
        """Test that root package (empty path) is skipped."""
        npm_data = {
            "lockfileVersion": 3,
            "packages": {
                "": {
                    "name": "my-project",
                    "version": "1.0.0"
                },
                "node_modules/react": {
                    "version": "18.2.0"
                }
            }
        }
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
            json.dump(npm_data, f)
            temp_path = f.name
        
        try:
            packages = parse_npm_lock(temp_path)
            # Should only include react, not the root package
            self.assertEqual(len(packages), 1)
            self.assertEqual(packages[0][0], 'react')
        finally:
            os.unlink(temp_path)


class TestParseYarnLock(unittest.TestCase):
    """Test Yarn lock file parser."""
    
    def setUp(self):
        """Set up test fixtures."""
        self.test_dir = Path(__file__).parent / 'fixtures'
        self.sample_file = self.test_dir / 'sample_yarn.lock'
    
    def test_parse_yarn_lock_basic(self):
        """Test basic parsing of yarn.lock file."""
        yarn_content = '''# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

react@^18.2.0:
  version "18.2.0"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz"

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
'''
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.lock', delete=False) as f:
            f.write(yarn_content)
            temp_path = f.name
        
        try:
            packages = parse_yarn_lock(temp_path)
            self.assertGreaterEqual(len(packages), 2)
            
            package_dict = {pkg[0]: pkg[1] for pkg in packages}
            self.assertIn('react', package_dict)
            self.assertEqual(package_dict['react'], '18.2.0')
        finally:
            os.unlink(temp_path)
    
    def test_parse_yarn_lock_scoped_package(self):
        """Test parsing scoped packages in yarn.lock."""
        yarn_content = '''# THIS IS AN AUTOGENERATED FILE
"@babel/core@^7.27.4":
  version "7.27.4"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.27.4.tgz"
'''
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.lock', delete=False) as f:
            f.write(yarn_content)
            temp_path = f.name
        
        try:
            packages = parse_yarn_lock(temp_path)
            self.assertEqual(len(packages), 1)
            self.assertEqual(packages[0], ('@babel/core', '7.27.4'))
        finally:
            os.unlink(temp_path)


class TestParsePnpmLock(unittest.TestCase):
    """Test pnpm lock file parser."""
    
    def setUp(self):
        """Set up test fixtures."""
        self.test_dir = Path(__file__).parent / 'fixtures'
        self.sample_file = self.test_dir / 'sample_pnpm_lock.yaml'
    
    def test_parse_pnpm_lock_basic(self):
        """Test basic parsing of pnpm-lock.yaml file."""
        pnpm_content = '''lockfileVersion: '6.0'

packages:
  /react/18.2.0:
    resolution: {integrity: sha512-...}
    dev: false
  
  /@babel/core/7.27.4:
    resolution: {integrity: sha512-...}
    dev: false
'''
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.yaml', delete=False) as f:
            f.write(pnpm_content)
            temp_path = f.name
        
        try:
            packages = parse_pnpm_lock(temp_path)
            self.assertGreaterEqual(len(packages), 2)
            
            package_names = [pkg[0] for pkg in packages]
            self.assertIn('react', package_names)
            self.assertIn('@babel/core', package_names)
        finally:
            os.unlink(temp_path)


class TestParseDenoLock(unittest.TestCase):
    """Test Deno lock file parser."""
    
    def setUp(self):
        """Set up test fixtures."""
        self.test_dir = Path(__file__).parent / 'fixtures'
        self.sample_file = self.test_dir / 'sample_deno.lock'
    
    def test_parse_deno_lock_basic(self):
        """Test basic parsing of deno.lock file."""
        deno_data = {
            "version": "3",
            "npm": {
                "specifiers": {
                    "react@18.2.0": "react@18.2.0",
                    "@babel/core@7.27.4": "@babel/core@7.27.4"
                }
            }
        }
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.lock', delete=False) as f:
            json.dump(deno_data, f)
            temp_path = f.name
        
        try:
            packages = parse_deno_lock(temp_path)
            self.assertGreaterEqual(len(packages), 2)
            
            package_dict = {pkg[0]: pkg[1] for pkg in packages}
            self.assertIn('react', package_dict)
            self.assertEqual(package_dict['react'], '18.2.0')
        finally:
            os.unlink(temp_path)


class TestParseLockFile(unittest.TestCase):
    """Test unified parse_lock_file function."""
    
    def test_parse_lock_file_auto_detect(self):
        """Test auto-detection in parse_lock_file."""
        npm_data = {
            "lockfileVersion": 3,
            "packages": {
                "node_modules/react": {"version": "18.2.0"}
            }
        }
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='package-lock.json', delete=False) as f:
            json.dump(npm_data, f)
            temp_path = f.name
        
        try:
            packages = parse_lock_file(temp_path, format_type=None)
            self.assertGreater(len(packages), 0)
        finally:
            os.unlink(temp_path)
    
    def test_parse_lock_file_explicit_format(self):
        """Test explicit format specification in parse_lock_file."""
        npm_data = {
            "lockfileVersion": 3,
            "packages": {
                "node_modules/react": {"version": "18.2.0"}
            }
        }
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
            json.dump(npm_data, f)
            temp_path = f.name
        
        try:
            packages = parse_lock_file(temp_path, format_type='npm')
            self.assertGreater(len(packages), 0)
        finally:
            os.unlink(temp_path)


if __name__ == '__main__':
    unittest.main()

